from typing import Any


def set_appearance_mode(mode: str) -> None: ...
def set_default_color_theme(theme: str) -> None: ...


class CTk:
    def title(self, text: str) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...
    def geometry(self, geometry: str) -> None: ...
    def minsize(self, width: int, height: int) -> None: ...
    def grid_columnconfigure(self, index: int, weight: int) -> None: ...
    def grid_rowconfigure(self, index: int, weight: int) -> None: ...
    def bind(self, sequence: str, callback: Any) -> None: ...
    def after(self, delay: int, callback: Any) -> None: ...
    def mainloop(self) -> None: ...


class CTkToplevel(CTk):
    def transient(self, parent: Any) -> None: ...
    def grab_set(self) -> None: ...
    def update_idletasks(self) -> None: ...
    def winfo_rootx(self) -> int: ...
    def winfo_rooty(self) -> int: ...
    def winfo_width(self) -> int: ...
    def winfo_height(self) -> int: ...


class CTkFont:
    def __init__(self, size: int = ..., weight: str = ...) -> None: ...


class ThemeManager:
    theme: dict[str, Any]


class _BaseWidget:
    def grid(self, **kwargs: Any) -> None: ...
    def grid_columnconfigure(self, index: int, weight: int) -> None: ...
    def grid_rowconfigure(self, index: int, weight: int) -> None: ...
    def configure(self, **kwargs: Any) -> None: ...


class CTkFrame(_BaseWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkScrollableFrame(CTkFrame):
    pass


class CTkLabel(_BaseWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkButton(_BaseWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class CTkEntry(_BaseWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def insert(self, index: int, text: str) -> None: ...
    def get(self) -> str: ...


class CTkTextbox(_BaseWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def insert(self, index: str, text: str) -> None: ...
    def get(self, start: str, end: str) -> str: ...

